version: 1
formatters:
  simple_formatter:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  file_handler_debug:
    class: logging.FileHandler
    filename: ml_log.debug
    level: DEBUG
    formatter: simple_formatter
  file_handler_warn:
    class: logging.FileHandler
    filename: ml_log.warn
    level: WARN
    formatter: simple_formatter
  stream_handler_info:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: INFO
    formatter: simple_formatter
loggers:
  asset:
    level: DEBUG
    handlers: [file_handler_debug, file_handler_warn, stream_handler_info]
    propagate: no
root:
  level: DEBUG
  handlers: [file_handler_debug, file_handler_warn, stream_handler_info]